# Generated by Django 4.1.5 on 2024-07-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('index', 'timestamp')},
        ),
    ]
